### ISSUE TITLE
Our Beliefs Page

### ISSUE THREAD

**Issue by TravFarr** [robertbravery/MVBCWeb#4]
Finished the Our Beliefs page and pushed it to feature/ourbeliefs. I'm encountering a problem though because I can't get rid of your changes from earlier, so there's an h1 tag on top that shouldn't be there. I can't figure out how to completely over-ride your version though, unfortunately. I was hoping for some help with this. In the mean time, I'll continue creating the other pages.

**Comment by robertbravery** [comment]
Hi Travis,

Ok did you try and just delete the H1 tag. Then push it back up to GitHub again.

If you still don't come right, let me know.

Cheers

Robert

**Comment by robertbravery** [comment]
I've merged all other branches into master except "Our Beliefs".

Once you have tried to delete the H1 tag, and it works, let me know. I will merge. If not, I will delete it and the push and merge.

You can safely delete your local branches. I will delete the repository branches.

**Comment by TravFarr** [comment]
The H1 tag doesn't come up when I open the file in my editor. It only shows in the preview inside of Source Tree--so I've been unable to delete the tag.

**Comment by robertbravery** [comment]
OK, did you push it again to GitHub?

If so, and it still does not work. Let me know and I will delete it manually my site. Then you can branch again from master

**Comment by TravFarr** [comment]
I'm pretty sure I tried that and it didn't work. I'm not sure what's up with that. If you can delete it, that would be great. I'll just re-do it. Thanks man.

**Comment by robertbravery** [comment]
I've fixed the beliefs file. I've deleted the H1 tag, committed and pushed it to the branch.
I've also merged the branch to master.

Do a pull on the branch and see if the updates get pulled down.

If so, then we can go ahead and delete the branch and close the issue.

Well done, I like the way this is working. I like the fact that we have had this issue. It just highlights the process and collaboration functionality.

**Comment by TravFarr** [comment]
(https://cloud.githubusercontent.com/assets/19972125/16143604/0df79f6c-346e-11e6-8c2c-2f89275ed0bf.jpg) - Photo 1

It pops up that you've submitted a pull request, but if I go in and look at the file, I still see this (see photo 2): 

(https://cloud.githubusercontent.com/assets/19972125/16143623/2921a44a-346e-11e6-8985-aea5e3c5ea8b.jpg) - Photo 2

Also, when you merge the branches with master, shouldn't they disappear from my client? See photo below. 
(https://cloud.githubusercontent.com/assets/19972125/16143638/48cabf8e-346e-11e6-9aba-1487845e8bd0.jpg) - Photo 3

**Comment by robertbravery** [comment]
The branches have not been deleted yet, so you will still see them under the remotes

Ok, first create a new branche from master of the remote. Make sure you select check out branch, then delete all your other branches.

I'm going to delete the remote branches. We will only have one in the remote, ie master.
